name: README_CODE
description: 'Action para incluir bloco de código no markdown'
author: 'Fernando Sousa'
inputs:
  owner:
    description: 'repo owner'
    required: true
  repo:
    description: 'repo'
    required: true

jobs:
  readme_code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: |
          git config --global user.email "fernandosousa.ti@gmail.com"
          git config --global user.name "Fernando Sousa|Actions"
          git clone https://github.com/${{inputs.owner}}/${{inputs.repo}}.git       
          python3 .github/workflows/readme_code.py ${{inputs.repo}}
          cd ${{inputs.repo}}
          git add README.md
          git commit -m 'alteração readme'
          git push origin master
runs:
  using: 'docker'
  image: 'Dockerfile'