name: README_CODE
description: 'Action para incluir bloco de código no markdown'
author: 'Fernando Sousa'
inputs:
  owner:
    description: 'repo owner'
    required: true
  repo:
    description: 'repo'
    required: true
  access_token:
    description: 'access token'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'